INSERT INTO DMOls.D_CLIENTE (
    CODIGO_CLIENTE,
    PREFIXO_ZIPCODE,
    CIDADE,
    ESTADO
)
SELECT
    S.CUSTOMER_ID AS CODIGO_CLIENTE,
    ISNULL(S.CUSTOMER_ZIP_CODE_PREFIX, 0.0) AS PREFIXO_ZIPCODE,
    ISNULL(UPPER(TRIM(S.CUSTOMER_CITY)), 'NAO LOCALIZADO') AS CIDADE,
    ISNULL(UPPER(TRIM(S.CUSTOMER_STATE)), 'NAO LOCALIZADO') AS ESTADO
FROM StgOls.STG_OLS_CUSTOMERS S
LEFT JOIN DMOls.D_CLIENTE D ON D.CODIGO_CLIENTE = S.CUSTOMER_ID
WHERE D.CODIGO_CLIENTE IS NULL