UPDATE DMOls.D_CLIENTE SET
    PREFIXO_ZIPCODE = ISNULL(S.CUSTOMER_ZIP_CODE_PREFIX, 0.0),
    CIDADE = ISNULL(UPPER(TRIM(S.CUSTOMER_CITY)), 'NAO LOCALIZADO'),
    ESTADO = ISNULL(UPPER(TRIM(S.CUSTOMER_STATE)), 'NAO LOCALIZADO'),
    DATA_PROCESSAMENTO = GETDATE()
FROM StgOls.STG_OLS_CUSTOMERS S
INNER JOIN DMOls.D_CLIENTE D ON D.CODIGO_CLIENTE = S.CUSTOMER_ID 
WHERE D.CODIGO_CLIENTE = S.CUSTOMER_ID