UPDATE DMOls.F_ORDEM_ITEM SET 
    SK_D_CLIENTE = ISNULL(DC.SK_D_CLIENTE,-1),
    SK_D_VENDEDOR = ISNULL(DV.SK_D_VENDEDOR,-1),
    STATUS = ISNULL(UPPER(TRIM(S.ORDER_STATUS)),'NAO LOCALIZADO'),
    TIPO_PAGAMENTO = ISNULL(UPPER(TRIM(REPLACE(S.PAYMENT_TYPE, '_', ' '))), 'NAO LOCALIZADO'),
    DATA_ORDEM_COMPRA = S.ORDER_PURCHASE_TIMESTAMP,
    DATA_ORDEM_APROVACAO = S.ORDER_APPROVED_AT,
    DATA_DESPACHO = S.ORDER_DELIVERED_CARRIER_DATE,
    DATA_ENTREGA_CLIENTE = S.ORDER_DELIVERED_CUSTOMER_DATE,
    DATA_ESTIMATIVA_ENTREGUA = S.ORDER_ESTIMATED_DELIVERY_DATE,
    TOTAL_PRECO_ITEM = ISNULL(S.TOTAL_ITEM_PRICE, 0),
    TOTAL_PRECO_FRETE = ISNULL(S.TOTAL_FREIGHT_VALUE, 0),
    QUANTIDADE_PARCELAS = ISNULL(S.MAX_PAYMENT_SEQUENTIAL, 0),
    QUANTIDADE_INSTALLMENTS = ISNULL(S.MAX_PAYMENT_INSTALLMENTS, 0),
    TOTAL_PRECO_PAGAMENTO = ISNULL(S.TOTAL_PAYMENT_VALUE, 0),
    DATA_PROCESSAMENTO = GETDATE()
FROM StgOls.STG_OLS_ORDER_ITEMS S
LEFT JOIN DMOls.D_CLIENTE DC ON S.CUSTOMER_ID = DC.CODIGO_CLIENTE 
LEFT JOIN DMOls.D_VENDEDOR DV ON S.SELLER_ID = DV.CODIGO_VENDEDOR 
LEFT JOIN DMOls.D_PRODUTO DP ON S.PRODUCT_ID = DP.CODIGO_PRODUTO 
INNER JOIN DMOls.F_ORDEM_ITEM F ON F.CODIGO_ORDEM = S.ORDER_ID AND F.SK_D_PRODUTO = DP.SK_D_PRODUTO 
WHERE F.CODIGO_ORDEM = S.ORDER_ID AND F.SK_D_PRODUTO = ISNULL(DP.SK_D_PRODUTO,-1)