INSERT INTO DMOls.F_ORDEM_ITEM (
    SK_D_CLIENTE,
    SK_D_VENDEDOR,
    SK_D_PRODUTO,
    CODIGO_ORDEM,
    STATUS,
    TIPO_PAGAMENTO,
    DATA_ORDEM_COMPRA,
    DATA_ORDEM_APROVACAO,
    DATA_DESPACHO,
    DATA_ENTREGA_CLIENTE,
    DATA_ESTIMATIVA_ENTREGUA,
    TOTAL_PRECO_ITEM,
    TOTAL_PRECO_FRETE,
    QUANTIDADE_PARCELAS,
    QUANTIDADE_INSTALLMENTS,
    TOTAL_PRECO_PAGAMENTO
)
SELECT 
    ISNULL(DC.SK_D_CLIENTE,-1) AS SK_D_CLIENTE,
    ISNULL(DV.SK_D_VENDEDOR,-1) AS SK_D_VENDEDOR,
    ISNULL(DP.SK_D_PRODUTO,-1) AS SK_D_PRODUTO,
    S.ORDER_ID AS CODIGO_ORDEM,
    ISNULL(UPPER(TRIM(S.ORDER_STATUS)),'NAO LOCALIZADO') AS STATUS,
    ISNULL(UPPER(TRIM(REPLACE(S.PAYMENT_TYPE, '_', ' '))), 'NAO LOCALIZADO') AS TIPO_PAGAMENTO,
    S.ORDER_PURCHASE_TIMESTAMP AS DATA_ORDEM_COMPRA,
    S.ORDER_APPROVED_AT AS DATA_ORDEM_APROVACAO,
    S.ORDER_DELIVERED_CARRIER_DATE AS DATA_DESPACHO,
    S.ORDER_DELIVERED_CUSTOMER_DATE AS DATA_ENTREGA_CLIENTE,
    S.ORDER_ESTIMATED_DELIVERY_DATE AS DATA_ESTIMATIVA_ENTREGUA,
    ISNULL(S.TOTAL_ITEM_PRICE, 0) AS TOTAL_PRECO_ITEM,
    ISNULL(S.TOTAL_FREIGHT_VALUE, 0) AS TOTAL_PRECO_FRETE,
    ISNULL(S.MAX_PAYMENT_SEQUENTIAL, 0) AS QUANTIDADE_PARCELAS,
    ISNULL(S.MAX_PAYMENT_INSTALLMENTS, 0) AS QUANTIDADE_INSTALLMENTS,
    ISNULL(S.TOTAL_PAYMENT_VALUE, 0) AS TOTAL_PRECO_PAGAMENTO
FROM StgOls.STG_OLS_ORDER_ITEMS S
LEFT JOIN DMOls.D_CLIENTE DC ON S.CUSTOMER_ID = DC.CODIGO_CLIENTE 
LEFT JOIN DMOls.D_VENDEDOR DV ON S.SELLER_ID = DV.CODIGO_VENDEDOR 
LEFT JOIN DMOls.D_PRODUTO DP ON S.PRODUCT_ID = DP.CODIGO_PRODUTO 
LEFT JOIN DMOls.F_ORDEM_ITEM F ON F.CODIGO_ORDEM = S.ORDER_ID AND F.SK_D_PRODUTO = DP.SK_D_PRODUTO 
WHERE F.CODIGO_ORDEM IS NULL AND F.SK_D_PRODUTO IS NULL