
/*
 * CREATE SCHEMA StgOls
 * 		- Stages para o Data Mart Ols.
 * 
 * CREATE SCHEMA DMOls
 * 		- Data Mart Ols.
*/

/*
 * DMOls.F_ORDEM_ITEM
 * 
 * 		- Select
 * 		- Create Table
 * 		- Create Index
 * 		- Insert Into DMOls.F_ORDEM_ITEM
 * 		- Update DMOls.F_ORDEM_ITEM
 * 
 */

CREATE TABLE DMOls.F_ORDEM_ITEM (
	SK_F_ORDEM_ITEM INT IDENTITY(1,1) NOT NULL,
	SK_D_CLIENTE INT NULL,
	SK_D_VENDEDOR INT NULL,
	SK_D_PRODUTO INT NULL,
	CODIGO_ORDEM VARCHAR(255) NULL,
	STATUS VARCHAR(255) NULL,
	TIPO_PAGAMENTO VARCHAR(255) NULL,
	DATA_ORDEM_COMPRA DATETIME NULL,
	DATA_ORDEM_APROVACAO DATETIME NULL,
	DATA_DESPACHO DATETIME NULL,
	DATA_ENTREGA_CLIENTE DATETIME NULL,
	DATA_ESTIMATIVA_ENTREGUA DATETIME NULL,
	TOTAL_PRECO_ITEM NUMERIC(12,6) NULL,
	TOTAL_PRECO_FRETE NUMERIC(12,6) NULL,
	QUANTIDADE_PARCELAS INT NULL,
	QUANTIDADE_INSTALLMENTS INT NULL,
	TOTAL_PRECO_PAGAMENTO NUMERIC(12,6) NULL,
	DATA_PROCESSAMENTO DATETIME NULL DEFAULT GETDATE()
);

CREATE INDEX IDX_F_ORDEM_ITEM
ON DMOls.F_ORDEM_ITEM (SK_D_PRODUTO, CODIGO_ORDEM);


/*
 * DMOls.D_PRODUTO
 * 
 * 		- Select
 * 		- Create Table
 * 		- Create Index
 * 		- Insert -1 Reference
 * 		- Insert Into DMOls.D_PRODUTO
 * 		- Update DMOls.D_PRODUTO
 * 
 */


CREATE TABLE DMOls.D_PRODUTO (
	SK_D_PRODUTO INT IDENTITY(1,1) NOT NULL,
	CODIGO_PRODUTO VARCHAR(255) NULL,
	CATEGORIA VARCHAR(255) NULL,
	COMPRIMEIRO_NOME INT NULL,
	QUANTIDADE_FOTOS INT NULL,
	DATA_PROCESSAMENTO DATETIME NULL DEFAULT GETDATE()
);


SET IDENTITY_INSERT DMOls.D_PRODUTO ON
INSERT INTO DMOls.D_PRODUTO (SK_D_PRODUTO, CODIGO_PRODUTO, CATEGORIA, COMPRIMEIRO_NOME, QUANTIDADE_FOTOS)
VALUES (-1, 'NAO LOCALIZADO', 'NAO LOCALIZADO', -1, -1)
SET IDENTITY_INSERT DMOls.D_PRODUTO OFF


CREATE INDEX IDX_D_PRODUTO
ON DMOls.D_PRODUTO (CODIGO_PRODUTO);


/*
 * DMOls.D_VENDEDOR
 * 
 * 		- Select
 * 		- Create Table
 * 		- Create Index
 * 		- Insert -1 Reference
 * 		- Insert Into DMOls.D_VENDEDOR
 * 		- Update DMOls.D_VENDEDOR
 * 
 */


CREATE TABLE DMOls.D_VENDEDOR (
	SK_D_VENDEDOR INT IDENTITY(1,1) NOT NULL,
	CODIGO_VENDEDOR VARCHAR(255) NULL,
	PREFIXO_ZIPCODE INT NULL,
	CIDADE VARCHAR(255) NULL,
	ESTADO VARCHAR(255) NULL,
	DATA_PROCESSAMENTO DATETIME NULL DEFAULT GETDATE()
);


CREATE INDEX IDX_D_VENDEDOR
ON DMOls.D_VENDEDOR (CODIGO_VENDEDOR);


SET IDENTITY_INSERT DMOls.D_VENDEDOR ON
INSERT INTO DMOls.D_VENDEDOR (SK_D_VENDEDOR, CODIGO_VENDEDOR, PREFIXO_ZIPCODE, CIDADE, ESTADO)
VALUES (-1, 'NAO LOCALIZADO', -1, 'NAO LOCALIZADO', 'NAO LOCALIZADO')
SET IDENTITY_INSERT DMOls.D_VENDEDOR OFF;



/*
 * DMOls.D_CLIENTE
 * 
 * 		- Select
 * 		- Create Table
 * 		- Create Index
 * 		- Insert -1 Reference
 * 		- Insert Into DMOls.D_CLIENTE
 * 		- Update DMOls.D_CLIENTE
 * 
 */

CREATE TABLE DMOls.D_CLIENTE (
	SK_D_CLIENTE INT IDENTITY(1,1) NOT NULL,
	CODIGO_CLIENTE VARCHAR(255) NULL,
	PREFIXO_ZIPCODE INT NULL,
	CIDADE VARCHAR(255) NULL,
	ESTADO VARCHAR(255) NULL,
	DATA_PROCESSAMENTO DATETIME NULL DEFAULT GETDATE()
);


CREATE INDEX IDX_D_CLIENTE
ON DMOls.D_CLIENTE (CODIGO_CLIENTE);


SET IDENTITY_INSERT DMOls.D_CLIENTE ON
INSERT INTO DMOls.D_CLIENTE (SK_D_CLIENTE, CODIGO_CLIENTE, PREFIXO_ZIPCODE, CIDADE, ESTADO)
VALUES (-1, 'NAO LOCALIZADO', -1, 'NAO LOCALIZADO', 'NAO LOCALIZADO')
SET IDENTITY_INSERT DMOls.D_CLIENTE OFF;




